% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={College Basketball Data Analysis},
  pdfauthor={Xixi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{College Basketball Data Analysis}
\author{Xixi}
\date{2022-12-30}

\begin{document}
\maketitle

\hypertarget{setup}{%
\subsection{setup}\label{setup}}

\hypertarget{ux521dux6b65ux4e86ux89e3ux6570ux636eux6784ux6210}{%
\subsection{初步了解数据构成}\label{ux521dux6b65ux4e86ux89e3ux6570ux636eux6784ux6210}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(cbb)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 2,455
## Columns: 24
## $ TEAM       <chr> "North Carolina", "Wisconsin", "Michigan", "Texas Tech", "G~
## $ CONF       <chr> "ACC", "B10", "B10", "B12", "WCC", "SEC", "B10", "ACC", "AC~
## $ G          <dbl> 40, 40, 40, 38, 39, 40, 38, 39, 38, 39, 40, 40, 40, 40, 36,~
## $ W          <dbl> 33, 36, 33, 31, 37, 29, 30, 35, 35, 33, 35, 36, 32, 35, 27,~
## $ ADJOE      <dbl> 123.3, 129.1, 114.4, 115.2, 117.8, 117.2, 121.5, 125.2, 123~
## $ ADJDE      <dbl> 94.9, 93.6, 90.4, 85.2, 86.3, 96.2, 93.7, 90.6, 89.9, 91.5,~
## $ BARTHAG    <dbl> 0.9531, 0.9758, 0.9375, 0.9696, 0.9728, 0.9062, 0.9522, 0.9~
## $ EFG_O      <dbl> 52.6, 54.8, 53.9, 53.5, 56.6, 49.9, 54.6, 56.6, 55.2, 51.7,~
## $ EFG_D      <dbl> 48.1, 47.7, 47.7, 43.0, 41.1, 46.0, 48.0, 46.5, 44.7, 48.1,~
## $ TOR        <dbl> 15.4, 12.4, 14.0, 17.7, 16.2, 18.1, 14.6, 16.3, 14.7, 16.2,~
## $ TORD       <dbl> 18.2, 15.8, 19.5, 22.8, 17.1, 16.1, 18.7, 18.6, 17.5, 18.6,~
## $ ORB        <dbl> 40.7, 32.1, 25.5, 27.4, 30.0, 42.0, 32.5, 35.8, 30.4, 41.3,~
## $ DRB        <dbl> 30.0, 23.7, 24.9, 28.7, 26.2, 29.7, 29.4, 30.2, 25.4, 25.0,~
## $ FTR        <dbl> 32.3, 36.2, 30.7, 32.9, 39.0, 51.8, 28.4, 39.8, 29.1, 34.3,~
## $ FTRD       <dbl> 30.4, 22.4, 30.0, 36.6, 26.9, 36.8, 22.7, 23.9, 26.3, 31.6,~
## $ `2P_O`     <dbl> 53.9, 54.8, 54.7, 52.8, 56.3, 50.0, 53.4, 55.9, 52.5, 51.0,~
## $ `2P_D`     <dbl> 44.6, 44.7, 46.8, 41.9, 40.0, 44.9, 47.6, 46.3, 45.7, 46.3,~
## $ `3P_O`     <dbl> 32.7, 36.5, 35.2, 36.5, 38.2, 33.2, 37.9, 38.7, 39.5, 35.5,~
## $ `3P_D`     <dbl> 36.2, 37.5, 33.2, 29.7, 29.0, 32.2, 32.6, 31.4, 28.9, 33.9,~
## $ ADJ_T      <dbl> 71.7, 59.3, 65.9, 67.5, 71.5, 65.9, 64.8, 66.4, 60.7, 72.8,~
## $ WAB        <dbl> 8.6, 11.3, 6.9, 7.0, 7.7, 3.9, 6.2, 10.7, 11.1, 8.4, 8.9, 1~
## $ POSTSEASON <chr> "2ND", "2ND", "2ND", "2ND", "2ND", "2ND", "2ND", "Champions~
## $ SEED       <dbl> 1, 1, 3, 3, 1, 8, 4, 1, 1, 1, 2, 1, 7, 1, 4, 3, 6, 1, 2, 9,~
## $ YEAR       <dbl> 2016, 2015, 2018, 2019, 2017, 2014, 2013, 2015, 2019, 2017,~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(cbb}\SpecialCharTok{$}\NormalTok{SEED)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  1  3  8  4  2  7  6  9 11 10  5 NA 16 12 13 14 15
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2,455 x 24
##    TEAM      CONF      G     W ADJOE ADJDE BARTHAG EFG_O EFG_D   TOR  TORD   ORB
##    <chr>     <chr> <dbl> <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 North Ca~ ACC      40    33  123.  94.9   0.953  52.6  48.1  15.4  18.2  40.7
##  2 Wisconsin B10      40    36  129.  93.6   0.976  54.8  47.7  12.4  15.8  32.1
##  3 Michigan  B10      40    33  114.  90.4   0.938  53.9  47.7  14    19.5  25.5
##  4 Texas Te~ B12      38    31  115.  85.2   0.970  53.5  43    17.7  22.8  27.4
##  5 Gonzaga   WCC      39    37  118.  86.3   0.973  56.6  41.1  16.2  17.1  30  
##  6 Kentucky  SEC      40    29  117.  96.2   0.906  49.9  46    18.1  16.1  42  
##  7 Michigan  B10      38    30  122.  93.7   0.952  54.6  48    14.6  18.7  32.5
##  8 Duke      ACC      39    35  125.  90.6   0.976  56.6  46.5  16.3  18.6  35.8
##  9 Virginia  ACC      38    35  123   89.9   0.974  55.2  44.7  14.7  17.5  30.4
## 10 North Ca~ ACC      39    33  121   91.5   0.962  51.7  48.1  16.2  18.6  41.3
## # ... with 2,445 more rows, and 12 more variables: DRB <dbl>, FTR <dbl>,
## #   FTRD <dbl>, `2P_O` <dbl>, `2P_D` <dbl>, `3P_O` <dbl>, `3P_D` <dbl>,
## #   ADJ_T <dbl>, WAB <dbl>, POSTSEASON <chr>, SEED <dbl>, YEAR <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb13}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 347 x 23
##    TEAM      CONF      G     W ADJOE ADJDE BARTHAG EFG_O EFG_D   TOR  TORD   ORB
##    <chr>     <chr> <dbl> <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 Indiana   B10      36    29  121   89.7   0.969  54.7  44    19.3  20.9  39  
##  2 Gonzaga   WCC      34    31  119.  90.2   0.960  54.9  44.9  17.2  20.8  37.8
##  3 Kansas    B12      37    31  112.  86.2   0.951  53.3  41.5  20.3  18.4  33.8
##  4 Louisvil~ BE       40    35  116.  84.5   0.974  50.6  44.8  18.3  27    38.2
##  5 Georgeto~ BE       32    25  108.  85     0.938  51.1  43    20.1  22.4  30.4
##  6 Miami FL  ACC      36    29  112.  90.8   0.921  51.9  45.7  16.7  18.4  31.3
##  7 Ohio St.  B10      37    29  114.  89.4   0.941  50.6  45.4  16.2  20.7  31.8
##  8 Duke      ACC      36    30  118.  91.5   0.951  53.9  45.5  15.6  20.4  28.8
##  9 Michigan~ B10      35    26  111.  87.8   0.939  50.6  44.5  20.8  19.2  36.1
## 10 Marquette BE       35    26  113   93.2   0.902  49.6  46.2  20.9  19.5  38.4
## # ... with 337 more rows, and 11 more variables: DRB <dbl>, FTR <dbl>,
## #   FTRD <dbl>, `2P_O` <dbl>, `2P_D` <dbl>, `3P_O` <dbl>, `3P_D` <dbl>,
## #   ADJ_T <dbl>, WAB <dbl>, POSTSEASON <chr>, SEED <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(cbb}\SpecialCharTok{$}\NormalTok{TEAM) }\CommentTok{\#Seed的区间是1{-}16，可以有重合的Seed，team总数是68}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] "North Carolina"         "Wisconsin"              "Michigan"              
##   [4] "Texas Tech"             "Gonzaga"                "Kentucky"              
##   [7] "Duke"                   "Virginia"               "Villanova"             
##  [10] "Connecticut"            "Louisville"             "Notre Dame"            
##  [13] "Florida St."            "Purdue"                 "Kansas"                
##  [16] "Kansas St."             "Xavier"                 "Arizona"               
##  [19] "Oregon"                 "Florida"                "Michigan St."          
##  [22] "Dayton"                 "Ohio St."               "Marquette"             
##  [25] "Syracuse"               "Oklahoma"               "Loyola Chicago"        
##  [28] "South Carolina"         "Auburn"                 "Wichita St."           
##  [31] "Duquesne"               "Fordham"                "George Mason"          
##  [34] "George Washington"      "La Salle"               "Massachusetts"         
##  [37] "Rhode Island"           "Richmond"               "Saint Joseph's"        
##  [40] "Saint Louis"            "St. Bonaventure"        "Davidson"              
##  [43] "VCU"                    "Boston College"         "Clemson"               
##  [46] "Georgia Tech"           "Miami FL"               "Pittsburgh"            
##  [49] "Virginia Tech"          "Wake Forest"            "North Carolina St."    
##  [52] "Binghamton"             "Hartford"               "Maine"                 
##  [55] "New Hampshire"          "Stony Brook"            "UMass Lowell"          
##  [58] "UMBC"                   "Vermont"                "Albany"                
##  [61] "East Carolina"          "Houston"                "Memphis"               
##  [64] "South Florida"          "Temple"                 "Tulane"                
##  [67] "Tulsa"                  "UCF"                    "SMU"                   
##  [70] "Florida Gulf Coast"     "Jacksonville"           "Kennesaw St."          
##  [73] "Lipscomb"               "Northern Kentucky"      "Stetson"               
##  [76] "USC Upstate"            "NJIT"                   "North Florida"         
##  [79] "North Alabama"          "Illinois"               "Minnesota"             
##  [82] "Nebraska"               "Northwestern"           "Penn St."              
##  [85] "Rutgers"                "Indiana"                "Iowa"                  
##  [88] "Maryland"               "TCU"                    "Oklahoma St."          
##  [91] "Texas"                  "Baylor"                 "Iowa St."              
##  [94] "West Virginia"          "Creighton"              "DePaul"                
##  [97] "Seton Hall"             "Georgetown"             "St. John's"            
## [100] "Butler"                 "Providence"             "Idaho"                 
## [103] "Idaho St."              "Montana"                "Montana St."           
## [106] "North Dakota"           "Northern Arizona"       "Northern Colorado"     
## [109] "Portland St."           "Sacramento St."         "Southern Utah"         
## [112] "Weber St."              "Eastern Washington"     "Campbell"              
## [115] "Charleston Southern"    "Gardner Webb"           "High Point"            
## [118] "Liberty"                "Longwood"               "Presbyterian"          
## [121] "Radford"                "UNC Asheville"          "Winthrop"              
## [124] "Coastal Carolina"       "Hampton"                "Cal Poly"              
## [127] "Cal St. Fullerton"      "Cal St. Northridge"     "Hawaii"                
## [130] "Long Beach St."         "UC Davis"               "UC Riverside"          
## [133] "UC Santa Barbara"       "UC Irvine"              "College of Charleston" 
## [136] "Delaware"               "Drexel"                 "Elon"                  
## [139] "Hofstra"                "James Madison"          "Towson"                
## [142] "UNC Wilmington"         "William & Mary"         "Northeastern"          
## [145] "Charlotte"              "FIU"                    "Florida Atlantic"      
## [148] "Louisiana Tech"         "Marshall"               "Middle Tennessee"      
## [151] "North Texas"            "Old Dominion"           "Rice"                  
## [154] "Southern Miss"          "UTEP"                   "UTSA"                  
## [157] "Western Kentucky"       "UAB"                    "Cleveland St."         
## [160] "Detroit"                "Green Bay"              "Illinois Chicago"      
## [163] "Milwaukee"              "Oakland"                "Wright St."            
## [166] "Youngstown St."         "Valparaiso"             "IUPUI"                 
## [169] "Brown"                  "Columbia"               "Cornell"               
## [172] "Dartmouth"              "Penn"                   "Princeton"             
## [175] "Yale"                   "Harvard"                "Canisius"              
## [178] "Fairfield"              "Iona"                   "Marist"                
## [181] "Monmouth"               "Niagara"                "Quinnipiac"            
## [184] "Rider"                  "Saint Peter's"          "Siena"                 
## [187] "Manhattan"              "Akron"                  "Ball St."              
## [190] "Bowling Green"          "Central Michigan"       "Eastern Michigan"      
## [193] "Kent St."               "Miami OH"               "Northern Illinois"     
## [196] "Ohio"                   "Toledo"                 "Western Michigan"      
## [199] "Buffalo"                "Bethune Cookman"        "Coppin St."            
## [202] "Delaware St."           "Florida A&M"            "Howard"                
## [205] "Maryland Eastern Shore" "Morgan St."             "Norfolk St."           
## [208] "North Carolina A&T"     "North Carolina Central" "Savannah St."          
## [211] "South Carolina St."     "Bradley"                "Drake"                 
## [214] "Evansville"             "Illinois St."           "Indiana St."           
## [217] "Missouri St."           "Southern Illinois"      "Northern Iowa"         
## [220] "Air Force"              "Colorado St."           "Fresno St."            
## [223] "Nevada"                 "New Mexico"             "San Jose St."          
## [226] "UNLV"                   "Utah St."               "Boise St."             
## [229] "San Diego St."          "Wyoming"                "Bryant"                
## [232] "Central Connecticut"    "Fairleigh Dickinson"    "LIU Brooklyn"          
## [235] "Mount St. Mary's"       "Sacred Heart"           "St. Francis NY"        
## [238] "St. Francis PA"         "Wagner"                 "Robert Morris"         
## [241] "Austin Peay"            "Eastern Illinois"       "Eastern Kentucky"      
## [244] "Jacksonville St."       "Morehead St."           "Murray St."            
## [247] "SIU Edwardsville"       "Southeast Missouri St." "Tennessee Martin"      
## [250] "Tennessee St."          "Tennessee Tech"         "Belmont"               
## [253] "Arizona St."            "California"             "Colorado"              
## [256] "Oregon St."             "Stanford"               "USC"                   
## [259] "Washington"             "Washington St."         "UCLA"                  
## [262] "Utah"                   "American"               "Army"                  
## [265] "Boston University"      "Bucknell"               "Colgate"               
## [268] "Holy Cross"             "Lehigh"                 "Loyola MD"             
## [271] "Navy"                   "Lafayette"              "Appalachian St."       
## [274] "Arkansas Little Rock"   "Arkansas St."           "Georgia Southern"      
## [277] "Louisiana Lafayette"    "Louisiana Monroe"       "South Alabama"         
## [280] "Texas St."              "Troy"                   "UT Arlington"          
## [283] "Georgia St."            "Little Rock"            "Chattanooga"           
## [286] "East Tennessee St."     "Furman"                 "Mercer"                
## [289] "Samford"                "The Citadel"            "UNC Greensboro"        
## [292] "VMI"                    "Western Carolina"       "Wofford"               
## [295] "Alabama"                "Mississippi St."        "Missouri"              
## [298] "Tennessee"              "Texas A&M"              "Vanderbilt"            
## [301] "Arkansas"               "Georgia"                "LSU"                   
## [304] "Mississippi"            "Abilene Christian"      "Central Arkansas"      
## [307] "Houston Baptist"        "Incarnate Word"         "Lamar"                 
## [310] "McNeese St."            "New Orleans"            "Nicholls St."          
## [313] "Northwestern St."       "Sam Houston St."        "Southeastern Louisiana"
## [316] "Texas A&M Corpus Chris" "Stephen F. Austin"      "Denver"                
## [319] "IPFW"                   "Nebraska Omaha"         "Oral Roberts"          
## [322] "South Dakota"           "South Dakota St."       "Western Illinois"      
## [325] "North Dakota St."       "Fort Wayne"             "Alabama A&M"           
## [328] "Alabama St."            "Alcorn St."             "Arkansas Pine Bluff"   
## [331] "Grambling St."          "Jackson St."            "Mississippi Valley St."
## [334] "Prairie View A&M"       "Southern"               "Texas Southern"        
## [337] "Cal St. Bakersfield"    "Chicago St."            "Grand Canyon"          
## [340] "Seattle"                "UMKC"                   "UT Rio Grande Valley"  
## [343] "Utah Valley"            "New Mexico St."         "Cal Baptist"           
## [346] "Loyola Marymount"       "Pacific"                "Pepperdine"            
## [349] "Portland"               "Saint Mary's"           "San Diego"             
## [352] "San Francisco"          "Santa Clara"            "BYU"                   
## [355] "Cincinnati"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb14}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 351 x 23
##    TEAM      CONF      G     W ADJOE ADJDE BARTHAG EFG_O EFG_D   TOR  TORD   ORB
##    <chr>     <chr> <dbl> <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 Arizona   P12      38    33  116.  87.4   0.964  51.7  42.3  15.7  19.1  36.4
##  2 Florida   SEC      39    36  116.  88.4   0.958  52.2  45.4  17.5  21.3  35.3
##  3 Virginia  ACC      37    30  115.  89.5   0.945  50.8  44.2  16.5  18.4  33.9
##  4 Wichita ~ MVC      35    34  116.  93     0.930  52.4  44.7  16.2  18.2  35  
##  5 Kansas    B12      35    25  119.  95.6   0.927  54.2  47.1  19.1  16.4  37.3
##  6 Michigan  B10      37    28  125   99.9   0.930  55.7  49.4  14.8  17.1  29.4
##  7 Villanova BE       34    29  115.  92.5   0.926  53.6  46.3  17.3  20    32.6
##  8 Wisconsin B10      38    30  123.  95.9   0.944  53.3  47.2  12.7  15.3  28.1
##  9 Creighton BE       35    27  125. 102.    0.914  58.9  48.5  15    14.8  27.7
## 10 Duke      ACC      35    26  126.  98.6   0.943  53.8  49.3  14.6  18.5  35.2
## # ... with 341 more rows, and 11 more variables: DRB <dbl>, FTR <dbl>,
## #   FTRD <dbl>, `2P_O` <dbl>, `2P_D` <dbl>, `3P_O` <dbl>, `3P_D` <dbl>,
## #   ADJ_T <dbl>, WAB <dbl>, POSTSEASON <chr>, SEED <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb20 }\CommentTok{\# 因为疫情，没有seed和postseason数据}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 353 x 22
##       RK TEAM      CONF      G     W ADJOE ADJDE BARTHAG EFG_O EFG_D   TOR  TORD
##    <dbl> <chr>     <chr> <dbl> <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl>
##  1     1 Kansas    B12      30    28  116.  87.7   0.962  53.7  43.7  18.7  18.6
##  2     2 Baylor    B12      30    26  114.  88.4   0.951  49.4  45.2  17.8  22.7
##  3     3 Gonzaga   WCC      33    31  121.  94.3   0.947  57.5  47.6  15.3  18.4
##  4     4 Dayton    A10      31    29  120.  93.4   0.944  59.7  46.6  18    18.8
##  5     5 Michigan~ B10      31    22  115.  91.3   0.933  52.6  43.3  18.1  15.8
##  6     6 Duke      ACC      31    25  115.  91.9   0.931  52.6  45.7  17.8  20.2
##  7     7 Creighton BE       30    24  121.  96.4   0.929  55.2  48.4  15.9  17.6
##  8     8 Ohio St.  B10      31    21  115.  92.6   0.92   52.3  46.2  19.1  18.3
##  9     9 Louisvil~ ACC      31    24  115.  93.9   0.912  52.5  45.1  18    17.4
## 10    10 San Dieg~ MWC      31    30  114.  92.8   0.912  54.6  45.2  16.2  21.3
## # ... with 343 more rows, and 10 more variables: ORB <dbl>, DRB <dbl>,
## #   FTR <dbl>, FTRD <dbl>, `2P_O` <dbl>, `2P_D` <dbl>, `3P_O` <dbl>,
## #   `3P_D` <dbl>, ADJ_T <dbl>, WAB <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb21 }\CommentTok{\# 21年没有postseason的数据，但是有seed}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 347 x 22
##    TEAM      CONF      G     W ADJOE ADJDE BARTHAG EFG_O EFG_D   TOR  TORD   ORB
##    <chr>     <chr> <dbl> <dbl> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
##  1 Michigan  B10      24    20  118.  91.1   0.952  54.9  44.9  16.3  15.1  29.4
##  2 Baylor    B12      24    22  123.  94.5   0.955  57.5  49.1  17.6  24.6  37.5
##  3 Illinois  B10      29    23  118.  90.4   0.954  55.6  46.6  18.2  16.1  33  
##  4 Gonzaga   WCC      26    26  125.  89.8   0.979  61    47.5  16.1  20.3  30.4
##  5 Iowa      B10      29    21  124.  95.7   0.949  54.6  48.3  13.3  16.3  30.7
##  6 Ohio St.  B10      30    21  122.  97     0.934  53.1  48.9  15.3  15    29.1
##  7 Houston   Amer     26    24  121.  90.9   0.963  51.3  42.9  16.3  21.6  39.4
##  8 Alabama   SEC      30    24  111   88.1   0.934  51.3  45.3  18.6  21.1  31.5
##  9 West Vir~ B12      27    18  116.  95.3   0.905  48.7  50.2  17    20.7  35.6
## 10 Texas     B12      26    19  114.  93.5   0.906  52.9  46.7  20.2  17.8  31.3
## # ... with 337 more rows, and 10 more variables: DRB <dbl>, FTR <dbl>,
## #   FTRD <dbl>, `2P_O` <dbl>, `2P_D` <dbl>, `3P_O` <dbl>, `3P_D` <dbl>,
## #   ADJ_T <dbl>, WAB <dbl>, SEED <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(cbb13}\SpecialCharTok{$}\NormalTok{CONF)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "B10"  "WCC"  "B12"  "BE"   "ACC"  "MWC"  "SEC"  "A10"  "P12"  "CUSA"
## [11] "MVC"  "OVC"  "Pat"  "SB"   "MAC"  "Sum"  "BSky" "WAC"  "Slnd" "Ivy" 
## [21] "SC"   "Horz" "BW"   "MAAC" "ASun" "AE"   "MEAC" "SWAC" "NEC"  "CAA" 
## [31] "BSth" "ind"  "GWC"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(cbb13}\SpecialCharTok{$}\NormalTok{CONF))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 33
\end{verbatim}

\hypertarget{ux4ee5ux4e0bux6b63ux5f0fux5f00ux59cbux6570ux636eux5206ux6790}{%
\subsection{以下正式开始数据分析}\label{ux4ee5ux4e0bux6b63ux5f0fux5f00ux59cbux6570ux636eux5206ux6790}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb13\_new }\OtherTok{=}\NormalTok{ cbb13 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2013}\NormalTok{)}
\NormalTok{cbb14\_new }\OtherTok{=}\NormalTok{ cbb14 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2014}\NormalTok{)}
\NormalTok{cbb15\_new }\OtherTok{=}\NormalTok{ cbb15 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2015}\NormalTok{)}
\NormalTok{cbb16\_new }\OtherTok{=}\NormalTok{ cbb16 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2016}\NormalTok{)}
\NormalTok{cbb17\_new }\OtherTok{=}\NormalTok{ cbb17 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2017}\NormalTok{)}
\NormalTok{cbb18\_new }\OtherTok{=}\NormalTok{ cbb18 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2018}\NormalTok{)}
\NormalTok{cbb19\_new }\OtherTok{=}\NormalTok{ cbb19 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2019}\NormalTok{)}
\NormalTok{cbb20\_new }\OtherTok{=}\NormalTok{ cbb20 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2020}\NormalTok{)}
\NormalTok{cbb21\_new }\OtherTok{=}\NormalTok{ cbb21 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{YEAR =} \DecValTok{2021}\NormalTok{)}

\NormalTok{cbb\_list }\OtherTok{=} \FunctionTok{list}\NormalTok{(cbb13\_new,cbb14\_new,cbb15\_new,cbb16\_new,cbb17\_new,cbb18\_new,cbb19\_new,cbb21\_new)}
\NormalTok{cbb\_all }\OtherTok{=} \FunctionTok{rbindlist}\NormalTok{(cbb\_list,}\AttributeTok{use.names =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{fill=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}R68\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}68\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}R64\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}64\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}R32\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}32\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}S16\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}16\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}E8\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}8\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}F4\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}4\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}2ND\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}2\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON[cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\SpecialCharTok{==} \StringTok{\textquotesingle{}Champions\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}1\textquotesingle{}}
\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{CONF[cbb\_all}\SpecialCharTok{$}\NormalTok{CONF }\SpecialCharTok{==} \StringTok{\textquotesingle{}ind\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \StringTok{\textquotesingle{}Ind\textquotesingle{}}

\NormalTok{cbb\_all }\OtherTok{\textless{}{-}}\NormalTok{ cbb\_all }\SpecialCharTok{\%\textgreater{}\%} 
        \FunctionTok{rename}\NormalTok{( }\StringTok{"two\_P\_O"} \OtherTok{=} \StringTok{"2P\_O"}\NormalTok{,}
                \StringTok{"two\_P\_D"} \OtherTok{=} \StringTok{"2P\_D"}\NormalTok{,}
                \StringTok{"three\_P\_O"} \OtherTok{=} \StringTok{"3P\_O"}\NormalTok{,}
                \StringTok{"three\_P\_D"} \OtherTok{=} \StringTok{"3P\_D"}\NormalTok{)}

\NormalTok{cbb\_all }\OtherTok{=}\NormalTok{ cbb\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{W\_ratio =}\NormalTok{ W}\SpecialCharTok{/}\NormalTok{G) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\StringTok{\textquotesingle{}YEAR\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}TEAM\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}SEED\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}POSTSEASON\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}CONF\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}G\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}W\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}W\_ratio\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}ADJOE\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}ADJDE\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}BARTHAG\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}EFG\_O\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}EFG\_D\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}TOR\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}TORD\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}ORB\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}DRB\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}FTR\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}FTRD\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}two\_P\_O\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}two\_P\_D\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}three\_P\_O\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}three\_P\_D\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}ADJ\_T\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}WAB\textquotesingle{}}\NormalTok{)}

\NormalTok{cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(cbb\_all}\SpecialCharTok{$}\NormalTok{POSTSEASON)}


\NormalTok{cbb\_all}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       YEAR             TEAM SEED POSTSEASON CONF  G  W   W_ratio ADJOE ADJDE
##    1: 2013          Indiana    1         16  B10 36 29 0.8055556 121.0  89.7
##    2: 2013          Gonzaga    1         32  WCC 34 31 0.9117647 118.9  90.2
##    3: 2013           Kansas    1         16  B12 37 31 0.8378378 111.6  86.2
##    4: 2013       Louisville    1          1   BE 40 35 0.8750000 115.9  84.5
##    5: 2013       Georgetown    2         64   BE 32 25 0.7812500 107.6  85.0
##   ---                                                                       
## 2798: 2021   Louisiana Tech   NA         NA CUSA 27 21 0.7777778 102.7  93.4
## 2799: 2021           Toledo   NA         NA  MAC 29 21 0.7241379 113.3 101.8
## 2800: 2021              UAB   NA         NA CUSA 27 22 0.8148148 102.5  94.6
## 2801: 2021 Eastern Kentucky   NA         NA  OVC 27 22 0.8148148 101.5 102.3
## 2802: 2021          Belmont   NA         NA  OVC 29 26 0.8965517 108.5 101.6
##       BARTHAG EFG_O EFG_D  TOR TORD  ORB  DRB  FTR FTRD two_P_O two_P_D
##    1:  0.9692  54.7  44.0 19.3 20.9 39.0 31.4 45.8 27.0    52.0    43.2
##    2:  0.9599  54.9  44.9 17.2 20.8 37.8 29.8 40.8 29.9    55.0    42.1
##    3:  0.9514  53.3  41.5 20.3 18.4 33.8 29.3 39.5 32.0    52.9    39.3
##    4:  0.9743  50.6  44.8 18.3 27.0 38.2 33.3 40.0 34.9    50.8    43.4
##    5:  0.9381  51.1  43.0 20.1 22.4 30.4 31.0 36.8 35.3    50.2    41.4
##   ---                                                                  
## 2798:  0.7479  50.5  45.6 18.4 18.8 27.1 23.4 35.3 26.4    49.7    46.4
## 2799:  0.7743  54.3  48.3 15.5 17.4 29.6 30.7 28.5 23.4    52.5    51.0
## 2800:  0.7153  48.6  47.0 15.6 23.6 29.0 25.4 29.9 27.1    49.4    46.1
## 2801:  0.4749  51.2  51.0 16.6 24.3 26.8 30.2 25.6 32.2    49.6    51.8
## 2802:  0.6786  56.3  49.3 16.6 20.3 26.1 27.2 27.9 24.6    59.4    48.2
##       three_P_O three_P_D ADJ_T  WAB
##    1:      40.3      30.4  67.8  7.8
##    2:      36.5      32.9  65.1  7.6
##    3:      36.4      30.3  67.7  7.5
##    4:      33.3      31.8  67.1  9.0
##    5:      35.3      30.7  62.5  6.6
##   ---                               
## 2798:      34.6      29.6  69.6 -1.7
## 2799:      37.7      29.5  69.1 -2.1
## 2800:      31.1      32.4  67.5 -2.7
## 2801:      35.8      33.0  75.1 -3.8
## 2802:      34.7      34.0  71.1 -1.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(CONF }\SpecialCharTok{==} \StringTok{\textquotesingle{}ind\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Empty data.table (0 rows and 25 cols): YEAR,TEAM,SEED,POSTSEASON,CONF,G...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(CONF }\SpecialCharTok{==} \StringTok{\textquotesingle{}Ind\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    YEAR                TEAM SEED POSTSEASON CONF  G  W   W_ratio ADJOE ADJDE
## 1: 2013         New Orleans   NA         NA  Ind 22  4 0.1818182  86.6 112.1
## 2: 2013 Cal St. Bakersfield   NA         NA  Ind 26 10 0.3846154  95.6 103.1
## 3: 2014                NJIT   NA         NA  Ind 25  9 0.3600000  95.1 110.4
## 4: 2015                NJIT   NA         NA  Ind 29 17 0.5862069 103.3 104.5
##    BARTHAG EFG_O EFG_D  TOR TORD  ORB  DRB  FTR FTRD two_P_O two_P_D three_P_O
## 1:  0.0490  44.9  54.0 24.4 21.2 27.4 36.6 38.8 41.5    46.1    52.7      27.1
## 2:  0.2950  46.8  51.5 20.7 21.9 30.1 30.2 35.4 52.4    44.7    51.3      33.7
## 3:  0.1529  48.0  50.3 18.6 18.8 26.1 32.7 38.8 47.5    45.0    49.8      35.7
## 4:  0.4644  52.3  46.4 20.5 19.0 28.8 33.8 39.0 44.1    49.8    44.6      37.1
##    three_P_D ADJ_T   WAB
## 1:      38.1  71.1 -14.9
## 2:      34.6  66.5 -10.4
## 3:      34.1  68.8 -12.4
## 4:      33.1  67.1  -6.2
\end{verbatim}

seed跟所在的conference有没有关系？或许存在某个conference占据很多席位的现象？与实力的关系？

seed与postseason的关系？ (需要思考出一种方法量化postseason的排名数据
重要‼️

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb\_all\_1 }\OtherTok{\textless{}{-}}\NormalTok{ cbb\_all }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(CONF,SEED) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(CONF,SEED) }\SpecialCharTok{\%\textgreater{}\%}  
  \FunctionTok{filter}\NormalTok{(SEED }\SpecialCharTok{!=} \StringTok{"NA"}\NormalTok{)}

\NormalTok{p\_seed }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all\_1, }\FunctionTok{aes}\NormalTok{(CONF, SEED, }\AttributeTok{fill =}\NormalTok{ n)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{(}\AttributeTok{color =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label=}\NormalTok{n)) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_continuous}\NormalTok{(}\AttributeTok{low=} \StringTok{"floralwhite"}\NormalTok{, }\AttributeTok{high=} \StringTok{"darkblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{breaks=}\FunctionTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{16}\NormalTok{,}\DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Conference"}\NormalTok{)}\SpecialCharTok{+}\FunctionTok{ylab}\NormalTok{(}\StringTok{"Seed"}\NormalTok{)}\SpecialCharTok{+}\FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Number of Teams in Seed 1 to Seed 16 For Every Conference Over 2013{-}2021"}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\# 2020的数据除外}
  \FunctionTok{coord\_fixed}\NormalTok{()}

\NormalTok{p\_seed}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 在tile上增加数字}
\CommentTok{\# 改为深色代表“大”，浅色代表“小”,空白代表NA(而并非将NA filter掉)}
\CommentTok{\# 不能忽略ind组的teams，虽然他们的seed都是NA}
\end{Highlighting}
\end{Shaded}

从历年数据(2013-2021,2020除外)来看，ACC,B10,B12在seed上有绝对的优势。
MEAC, NEC和SWAC排名比较落后b

按照CONF分组，将performance data绘制在box
plot上，寻找相差特别大的indicators。 分析..

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_1 }\OtherTok{\textless{}{-}}\FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{G)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of G among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"G"}\NormalTok{)}
\NormalTok{box\_1}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-6-1.pdf}

B10 is the highest, ACC, B12, BE, P12, SEC high.. Ind lowest GWC, Ivy,
SInd low

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{W)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of W among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"W"}\NormalTok{)}
\NormalTok{box\_2}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-7-1.pdf}

ACC, B10, B12, BE high

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_3 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{W\_ratio)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of W\_ratio among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"W\_ratio"}\NormalTok{)}
\NormalTok{box\_3}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-8-1.pdf}

ACC, B10, B12, BE high

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_4 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{ADJOE)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of ADJOE among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ADJOE"}\NormalTok{)}
\NormalTok{box\_4}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-9-1.pdf}

ACC, B12 highest, B10, BE high

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_5 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{ADJDE)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of ADJDE among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ADJDE"}\NormalTok{)}
\NormalTok{box\_5}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-10-1.pdf}

B10, B12 lowest.. ACC, BE, SEC low

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_6 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{BARTHAG)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of BARTHAG among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"BARTHAG"}\NormalTok{)}
\NormalTok{box\_6}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-11-1.pdf}

B12 highest B10, ACC high

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_7 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{EFG\_O)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of EFG\_O among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"EFG\_O"}\NormalTok{)}
\NormalTok{box\_7}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-12-1.pdf}

GWC, SWAC lowest 其他比较平均

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_8 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{EFG\_D)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of EFG\_D among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"EFG\_D"}\NormalTok{)}
\NormalTok{box\_8}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-13-1.pdf}

整体比较平均

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_9 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{TOR)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of TOR among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"TOR"}\NormalTok{)}
\NormalTok{box\_9}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-14-1.pdf}

整体比较平均

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_10 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{TORD)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of TORD among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"TORD"}\NormalTok{)}
\NormalTok{box\_10}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-15-1.pdf}

GWC highest ind high

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_11 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{ORB)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of ORB among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ORB"}\NormalTok{)}
\NormalTok{box\_11}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-16-1.pdf}

相对平均，Sum略低

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_12 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{DRB)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{"Boxplot of DRB among Conferences"}\NormalTok{,}\AttributeTok{x=} \StringTok{"CONF"}\NormalTok{, }\AttributeTok{y =} \StringTok{"DRB"}\NormalTok{)}
\NormalTok{box\_12}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-17-1.pdf}

ind highest GWC,

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_13 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{FTR)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_13}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_14 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{FTRD)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_14}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-19-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_15 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{two\_P\_O)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_15}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-20-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_16 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{two\_P\_D)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_16}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-21-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_17 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{three\_P\_O)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_17}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_18 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{three\_P\_D)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_18}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_19 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{ADJ\_T)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_19}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-24-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{box\_20 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(cbb\_all, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{CONF, }\AttributeTok{y=}\NormalTok{WAB)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x=}\FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle=}\DecValTok{45}\NormalTok{,}\AttributeTok{vjust=}\FloatTok{0.5}\NormalTok{))}
\NormalTok{box\_20}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-25-1.pdf}

\hypertarget{ux5bfbux627eux5f71ux54cdseedux7684ux56e0ux7d20}{%
\subsection{寻找影响seed的因素}\label{ux5bfbux627eux5f71ux54cdseedux7684ux56e0ux7d20}}

seed跟所在的conference有没有关系？或许存在某个conference占据很多席位的现象？与实力的关系？

seed与postseason的关系？ (需要思考出一种方法量化postseason的排名数据
重要‼️

The investigation in this area has been focused, traditionally, on men's
basketball teams (Ibáñez et al., 2003; Trninić et al., 2002). These
topics have been widely studied and some important trends have been
found: fields goals and defensive rebounds are the game performance
indicators that best discriminate between winning and losing teams in
basketball (Ibáñez et al., 2003; Ittenbach and Esters, 1995; Karipidis
et al., 2001). Sampaio et al.~(2010) suggest that winning teams
performance is due to the achievement of more opportunities to attempt
field-goals and also to the improvement in the decision making of the
players of the winning teams as well as a better strategic and tactical
environment. More recent studies have been exploring contextual factors
such as game location (home and away), game type (regular season and
playoff), game final score differences (close, balanced and unbalanced
games), players' gender (men and women), level of competition
(Euroleague, National Basketball Association, etc.) and age (senior and
junior) to establish better understanding of performance analysis
(Lorenzo et al., 2010).

The study of game performance as a function of the differences in the
final score of the game is becoming an important variable to consider.
Available literature has analyzed categories separately (Sampaio and
Janeira, 2003; Gómez et al., 2008). In balanced games (equal or below 12
points) the game performance indicators that discriminated between
winners and losers were defensive rebounds (Gómez et al., 2008), missed
3-point field goals (Gómez et al., 2009), field goals percentages and
defensive rebounds (Janeira et al., 1996) and in unbalanced games
(between 13 and 28 points of final score difference). Sampaio and
Janeira (2003) concluded that losing teams performed poorly in all
performance indicators. Gómez et al.~(2008) found that successful 2
points field-goals, defensive rebounds and assists discriminated between
winning and losing teams.

Conversely, only a few studies have analyzed performance in function of
a competition phase and never with high-level basketball competition. In
fact, most of professional leagues are organized in two phases: firstly,
all the teams compete against each other twice in a double round, with
the aim of add up victories to classification. Finally, only the top
classified teams (usually the best 8 teams of the regular season)
play-off for the championship. The qualifying round is organized in such
a way that best classified teams compete against the worst classified
team and so on in a knockout round the best of three or five games.
Thus, winning a game has a different importance: while in the regular
season you can lose three games in a row and remain in competition, if
you lose two of three, or three of five playoff games in a row you will
be eliminated. Sampaio and Janeira (2002) studied Portuguese
Professional Basketball League, which is a lower level competition
according to the International Basketball Federation (Gómez et al.,
2008). They pointed out that in the playoff games there were less ball
possessions (71.16) than in the regular season games (74.75). Hence, the
game rhythm was slower with a direct impact on the points per game,
reducing the final score. There are no more studies inspecting this
contrast between regular season and playoff games. Therefore, the aim of
the present study was to identify basketball game performance
indicators, which best discriminate between winners and losers in
regular season and playoff games.

做一个Correlation Analysis

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb\_noteam }\OtherTok{\textless{}{-}} \FunctionTok{subset}\NormalTok{(cbb\_all, }\AttributeTok{select =} \SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(TEAM,CONF))}
\NormalTok{cbb\_noteam}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       YEAR SEED POSTSEASON  G  W   W_ratio ADJOE ADJDE BARTHAG EFG_O EFG_D  TOR
##    1: 2013    1         16 36 29 0.8055556 121.0  89.7  0.9692  54.7  44.0 19.3
##    2: 2013    1         32 34 31 0.9117647 118.9  90.2  0.9599  54.9  44.9 17.2
##    3: 2013    1         16 37 31 0.8378378 111.6  86.2  0.9514  53.3  41.5 20.3
##    4: 2013    1          1 40 35 0.8750000 115.9  84.5  0.9743  50.6  44.8 18.3
##    5: 2013    2         64 32 25 0.7812500 107.6  85.0  0.9381  51.1  43.0 20.1
##   ---                                                                          
## 2798: 2021   NA         NA 27 21 0.7777778 102.7  93.4  0.7479  50.5  45.6 18.4
## 2799: 2021   NA         NA 29 21 0.7241379 113.3 101.8  0.7743  54.3  48.3 15.5
## 2800: 2021   NA         NA 27 22 0.8148148 102.5  94.6  0.7153  48.6  47.0 15.6
## 2801: 2021   NA         NA 27 22 0.8148148 101.5 102.3  0.4749  51.2  51.0 16.6
## 2802: 2021   NA         NA 29 26 0.8965517 108.5 101.6  0.6786  56.3  49.3 16.6
##       TORD  ORB  DRB  FTR FTRD two_P_O two_P_D three_P_O three_P_D ADJ_T  WAB
##    1: 20.9 39.0 31.4 45.8 27.0    52.0    43.2      40.3      30.4  67.8  7.8
##    2: 20.8 37.8 29.8 40.8 29.9    55.0    42.1      36.5      32.9  65.1  7.6
##    3: 18.4 33.8 29.3 39.5 32.0    52.9    39.3      36.4      30.3  67.7  7.5
##    4: 27.0 38.2 33.3 40.0 34.9    50.8    43.4      33.3      31.8  67.1  9.0
##    5: 22.4 30.4 31.0 36.8 35.3    50.2    41.4      35.3      30.7  62.5  6.6
##   ---                                                                        
## 2798: 18.8 27.1 23.4 35.3 26.4    49.7    46.4      34.6      29.6  69.6 -1.7
## 2799: 17.4 29.6 30.7 28.5 23.4    52.5    51.0      37.7      29.5  69.1 -2.1
## 2800: 23.6 29.0 25.4 29.9 27.1    49.4    46.1      31.1      32.4  67.5 -2.7
## 2801: 24.3 26.8 30.2 25.6 32.2    49.6    51.8      35.8      33.0  75.1 -3.8
## 2802: 20.3 26.1 27.2 27.9 24.6    59.4    48.2      34.7      34.0  71.1 -1.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cbb\_numeric }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(cbb\_noteam)}
\FunctionTok{cor}\NormalTok{(cbb\_numeric)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     YEAR         SEED    POSTSEASON           G           W
## YEAR        1.000000e+00 -0.002698321  2.606840e-17  0.02569547  0.06981960
## SEED       -2.698321e-03  1.000000000  6.207985e-01 -0.58732506 -0.64949619
## POSTSEASON  2.606840e-17  0.620798514  1.000000e+00 -0.71041707 -0.63044228
## G           2.569547e-02 -0.587325064 -7.104171e-01  1.00000000  0.59900994
## W           6.981960e-02 -0.649496188 -6.304423e-01  0.59900994  1.00000000
## W_ratio     7.909043e-02 -0.497665156 -4.209336e-01  0.24688950  0.92218215
## ADJOE       9.131307e-02 -0.745242957 -5.452042e-01  0.50318179  0.53640435
## ADJDE       1.222139e-01  0.697441023  4.965190e-01 -0.43560489 -0.53520796
## BARTHAG    -2.108640e-02 -0.826583963 -5.563362e-01  0.47730290  0.58020025
## EFG_O       2.815582e-01 -0.238977513 -2.201828e-01  0.12534482  0.39287362
## EFG_D       2.754242e-01  0.387082322  2.808696e-01 -0.23599336 -0.41169622
## TOR        -1.658327e-01  0.295070654  2.171816e-01 -0.21780356 -0.28846516
## TORD       -1.040273e-01  0.008041331 -6.397551e-02  0.01274405  0.12424538
## ORB        -3.020552e-01 -0.289248007 -2.100971e-01  0.19489314  0.21497709
## DRB        -3.273838e-01  0.133684858  4.250006e-02  0.01049354 -0.27279586
## FTR        -3.976374e-01  0.100146356  1.147566e-01 -0.08168851 -0.08453323
## FTRD       -2.101330e-01  0.256322264  1.893633e-01 -0.22833406 -0.20971571
## two_P_O     3.097290e-01 -0.216727247 -2.270620e-01  0.13788330  0.40615089
## two_P_D     2.692767e-01  0.389951961  2.602043e-01 -0.23399514 -0.36272597
## three_P_O   9.406957e-02 -0.178968952 -1.203743e-01  0.05825488  0.22193161
## three_P_D   8.840843e-02  0.176999493  1.546978e-01 -0.10770272 -0.27188569
## ADJ_T       3.849191e-01  0.045528785  8.647957e-02 -0.03062162 -0.05974349
## WAB         1.932118e-02 -0.918860161 -6.051154e-01  0.52988388  0.75219562
##                W_ratio       ADJOE       ADJDE     BARTHAG       EFG_O
## YEAR        0.07909043  0.09131307  0.12221388 -0.02108640  0.28155825
## SEED       -0.49766516 -0.74524296  0.69744102 -0.82658396 -0.23897751
## POSTSEASON -0.42093357 -0.54520419  0.49651905 -0.55633617 -0.22018277
## G           0.24688950  0.50318179 -0.43560489  0.47730290  0.12534482
## W           0.92218215  0.53640435 -0.53520796  0.58020025  0.39287362
## W_ratio     1.00000000  0.40199299 -0.43913681  0.47685663  0.41039532
## ADJOE       0.40199299  1.00000000 -0.30569757  0.77124097  0.57944211
## ADJDE      -0.43913681 -0.30569757  1.00000000 -0.78238307  0.12332725
## BARTHAG     0.47685663  0.77124097 -0.78238307  1.00000000  0.24943616
## EFG_O       0.41039532  0.57944211  0.12332725  0.24943616  1.00000000
## EFG_D      -0.38048073 -0.03280605  0.72162582 -0.41996274  0.18105818
## TOR        -0.24144010 -0.48625707  0.03279937 -0.31060137 -0.22212001
## TORD        0.14946538 -0.20661851 -0.26849674  0.02364230 -0.26395461
## ORB         0.16805035  0.21427616 -0.29912140  0.29180999 -0.29927482
## DRB        -0.33706479 -0.12016802  0.19409299 -0.19800271 -0.24761278
## FTR        -0.06649219 -0.15578230  0.04981837 -0.12547311 -0.26928595
## FTRD       -0.14107372 -0.23375403  0.11493084 -0.17897772 -0.31105501
## two_P_O     0.42224143  0.47686234  0.07066896  0.22103788  0.87453538
## two_P_D    -0.32232081 -0.06161376  0.66114791 -0.41292269  0.16873281
## three_P_O   0.23467369  0.47153760  0.12212670  0.19343972  0.73286022
## three_P_D  -0.27586368  0.02707331  0.42372682 -0.20237567  0.09918816
## ADJ_T      -0.05507189  0.10489943  0.26828104 -0.07556753  0.16278710
## WAB         0.65309358  0.76918624 -0.73452245  0.90111286  0.28640509
##                  EFG_D         TOR         TORD         ORB         DRB
## YEAR        0.27542415 -0.16583269 -0.104027294 -0.30205518 -0.32738384
## SEED        0.38708232  0.29507065  0.008041331 -0.28924801  0.13368486
## POSTSEASON  0.28086959  0.21718162 -0.063975510 -0.21009714  0.04250006
## G          -0.23599336 -0.21780356  0.012744054  0.19489314  0.01049354
## W          -0.41169622 -0.28846516  0.124245376  0.21497709 -0.27279586
## W_ratio    -0.38048073 -0.24144010  0.149465376  0.16805035 -0.33706479
## ADJOE      -0.03280605 -0.48625707 -0.206618507  0.21427616 -0.12016802
## ADJDE       0.72162582  0.03279937 -0.268496738 -0.29912140  0.19409299
## BARTHAG    -0.41996274 -0.31060137  0.023642296  0.29180999 -0.19800271
## EFG_O       0.18105818 -0.22212001 -0.263954612 -0.29927482 -0.24761278
## EFG_D       1.00000000 -0.11548167  0.011601361 -0.31564000  0.08053109
## TOR        -0.11548167  1.00000000  0.122210065  0.28472645  0.11983701
## TORD        0.01160136  0.12221006  1.000000000  0.12779351  0.37717806
## ORB        -0.31564000  0.28472645  0.127793509  1.00000000  0.09098754
## DRB         0.08053109  0.11983701  0.377178056  0.09098754  1.00000000
## FTR        -0.13244755  0.31099131  0.053506788  0.25109036  0.20017676
## FTRD        0.05954545  0.15920603  0.433564049  0.20385230  0.23945479
## two_P_O     0.12784636 -0.13807045 -0.186035978 -0.21380781 -0.24007829
## two_P_D     0.89648412 -0.11999896  0.058230115 -0.32695667  0.11833750
## three_P_O   0.14798455 -0.23653420 -0.256491758 -0.25767693 -0.16158528
## three_P_D   0.60419596 -0.03194697 -0.102342418 -0.11524514 -0.03006235
## ADJ_T       0.34568025 -0.07692382 -0.018527597 -0.09902328  0.05609538
## WAB        -0.40973188 -0.33669668  0.017542792  0.28616885 -0.20010168
##                    FTR        FTRD     two_P_O     two_P_D    three_P_O
## YEAR       -0.39763745 -0.21013302  0.30972897  0.26927665  0.094069572
## SEED        0.10014636  0.25632226 -0.21672725  0.38995196 -0.178968952
## POSTSEASON  0.11475658  0.18936329 -0.22706204  0.26020428 -0.120374290
## G          -0.08168851 -0.22833406  0.13788330 -0.23399514  0.058254880
## W          -0.08453323 -0.20971571  0.40615089 -0.36272597  0.221931609
## W_ratio    -0.06649219 -0.14107372  0.42224143 -0.32232081  0.234673688
## ADJOE      -0.15578230 -0.23375403  0.47686234 -0.06161376  0.471537595
## ADJDE       0.04981837  0.11493084  0.07066896  0.66114791  0.122126695
## BARTHAG    -0.12547311 -0.17897772  0.22103788 -0.41292269  0.193439721
## EFG_O      -0.26928595 -0.31105501  0.87453538  0.16873281  0.732860222
## EFG_D      -0.13244755  0.05954545  0.12784636  0.89648412  0.147984549
## TOR         0.31099131  0.15920603 -0.13807045 -0.11999896 -0.236534196
## TORD        0.05350679  0.43356405 -0.18603598  0.05823011 -0.256491758
## ORB         0.25109036  0.20385230 -0.21380781 -0.32695667 -0.257676932
## DRB         0.20017676  0.23945479 -0.24007829  0.11833750 -0.161585281
## FTR         1.00000000  0.31989465 -0.19443234 -0.12918913 -0.227969240
## FTRD        0.31989465  1.00000000 -0.28657328  0.05307194 -0.203624949
## two_P_O    -0.19443234 -0.28657328  1.00000000  0.13095647  0.321243130
## two_P_D    -0.12918913  0.05307194  0.13095647  1.00000000  0.120512508
## three_P_O  -0.22796924 -0.20362495  0.32124313  0.12051251  1.000000000
## three_P_D  -0.02990088  0.04915131  0.05202948  0.19863500  0.108845067
## ADJ_T      -0.01692490  0.08435091  0.21873694  0.34543421  0.006411229
## WAB        -0.08942701 -0.23069888  0.27181886 -0.39390011  0.199069298
##              three_P_D        ADJ_T         WAB
## YEAR        0.08840843  0.384919113  0.01932118
## SEED        0.17699949  0.045528785 -0.91886016
## POSTSEASON  0.15469777  0.086479572 -0.60511540
## G          -0.10770272 -0.030621622  0.52988388
## W          -0.27188569 -0.059743486  0.75219562
## W_ratio    -0.27586368 -0.055071887  0.65309358
## ADJOE       0.02707331  0.104899430  0.76918624
## ADJDE       0.42372682  0.268281036 -0.73452245
## BARTHAG    -0.20237567 -0.075567531  0.90111286
## EFG_O       0.09918816  0.162787104  0.28640509
## EFG_D       0.60419596  0.345680251 -0.40973188
## TOR        -0.03194697 -0.076923816 -0.33669668
## TORD       -0.10234242 -0.018527597  0.01754279
## ORB        -0.11524514 -0.099023276  0.28616885
## DRB        -0.03006235  0.056095381 -0.20010168
## FTR        -0.02990088 -0.016924901 -0.08942701
## FTRD        0.04915131  0.084350912 -0.23069888
## two_P_O     0.05202948  0.218736940  0.27181886
## two_P_D     0.19863500  0.345434207 -0.39390011
## three_P_O   0.10884507  0.006411229  0.19906930
## three_P_D   1.00000000  0.133102094 -0.21539403
## ADJ_T       0.13310209  1.000000000 -0.05893119
## WAB        -0.21539403 -0.058931187  1.00000000
\end{verbatim}

First of all, correlation ranges from -1 to 1. It gives us an indication
on two things:

The direction of the relationship between the 2 variables The strength
of the relationship between the 2 variables

Regarding the strength of the relationship: The more extreme the
correlation coefficient (the closer to -1 or 1), the stronger the
relationship. This also means that a correlation close to 0 indicates
that the two variables are independent, that is, as one variable
increases, there is no tendency in the other variable to either decrease
or increase.

按年份分出来，借鉴Honey Production Analysis Project (STOR320)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{corrplot}\NormalTok{(}\FunctionTok{cor}\NormalTok{(cbb\_noteam),}
  \AttributeTok{method =} \StringTok{"number"}\NormalTok{,}
  \AttributeTok{type =} \StringTok{"upper"} \CommentTok{\# show only upper side}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-29-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggcorrplot}\NormalTok{(}\FunctionTok{cor}\NormalTok{(cbb\_numeric),}\AttributeTok{type =} \StringTok{"lower"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{College-Basketball-Data-Analysis_files/figure-latex/unnamed-chunk-29-2.pdf}

年份(year)和其他的数据几乎是independent的关系
主要关注点在seed(主要是想通过regular
season的数据来预测seed)和postseason(探究seed和postseason的关系)上！

positively correlated: seed and postseason (r= 0.620798514), seed and
ADJDE (r= 0.697441023) negatively correlated: seed and WAB (r=
-0.918860161强相关), seed and BARTHAG (r= -0.826583963强相关), seed and
ADJOE (r= -0.745242957), seed and W (r= -0.649496188)

\hypertarget{modeling}{%
\subsection{Modeling}\label{modeling}}

set.seed()

Results Discussion

\end{document}
